name: Scrape Talk Locations

on:
  push:
    paths:
      - 'talks/**'
      - 'talkmap.ipynb'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install jupyter pandas requests beautifulsoup4 geopy
        pip install getorg --upgrade

    - name: Configure Git identity and authentication
      env:
        TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      run: |
        git config user.name "Clara Berestycki"
        git config user.email "claraberes@users.noreply.github.com"
        git remote set-url origin https://x-access-token:${TOKEN}@github.com/claraberes/claraberestycki.github.io.git

    - name: Pull the latest changes
      run: |
        git pull origin master

    - name: Run Jupyter Notebook
      run: |
        jupyter nbconvert --to notebook --execute talkmap.ipynb --output talkmap_out.ipynb

    - name: Commit and Push changes
      run: |
        git add .
        git commit -m "Automated update of talk locations" || echo "No changes to commit"
        git push origin HEAD:master
